#!/usr/bin/env ruby
# frozen_string_literal: true

require 'bundler'
begin
  Bundler.setup(:test)
rescue Bundler::BundlerError => e
  $stderr.puts e.message
  $stderr.puts 'Run `bundle install` to install missing gems'
  exit e.status_code
end
require 'allocation_stats'

$LOAD_PATH.unshift(File.join(File.dirname(__FILE__), '..', 'lib'))

stats = AllocationStats.trace do
  require 'iso-639.rb'
  ISO_639.find_by_code('en')
end

puts stats.allocations.group_by(:class).to_text
